name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
    tags-ignore:
      - 'v0.*' # alpha
      - 'v1.*' # release
  pull_request:
    branches: [ "main" ]
  workflow_call:
  workflow_dispatch:

jobs:
  client-webpack:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [12.x]
        theme: [dark, light]
        boxed: [default, boxed]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install apt dependencies
      run: |
        sudo apt-get install -y make

    - name: Install npm dependencies
      run: |
        npm install

    - name: Build codam-web-greeter
      run: |
        make build CLIENT_THEME=${{ matrix.theme }} CLIENT_THEME_BOXED=${{ matrix.boxed }}

    - name: Add dist folder to artifact
      working-directory: dist
      run: |
        zip -r ../codam-web-greeter.zip *

    - name: Add systemd folder to artifact as subfolder
      run: |
        zip -r codam-web-greeter.zip systemd

    - name: Rename artifact
      run: |
        mv codam-web-greeter.zip codam-web-greeter-${{ matrix.theme }}-${{ matrix.boxed }}.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: relzip-codam-web-greeter-${{ matrix.theme }}-${{ matrix.boxed }}
        path: codam-web-greeter-${{ matrix.theme }}-${{ matrix.boxed }}.zip
        retention-days: 1
